# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html

---
- hosts: all
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
        - "{{ ansible_user_id }}"
    - role: geerlingguy.ruby
      become: true
      vars:
        ruby_version: 2.5.1
    - { role: role-pip, tags: 'pip' }
    - { role: role-vim, tags: 'vim' }
    - { role: role-git, tags: 'git' }
    - { role: role-apt, tags: 'apt', when: "ansible_os_family == 'Debian'" }


  tasks:
    - name: ensure tmuxinator packages is at the latest version
      gem:
        name: tmuxinator
        state: latest

    # command 존재 여부로 zsh plugin 을 설치 하므로 하단에 배치해야함
    - import_role:
        name: role-zsh
      become: true
      tags: zsh
      vars:
        docker_users:
        - "{{ ansible_user_id }}"
