# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html


---
- hosts: all
  roles:

    - { role: role-apt, tags: 'apt', when: "ansible_os_family == 'Debian'" }
    - { role: role-docker, tags: 'docker' }
    - { role: role-pip, tags: 'pip' }
    - { role: role-vim, tags: 'vim' }
    - { role: role-git, tags: 'git' }
    # command 존재 여부로 zsh plugin 을 설치 하므로 하단에 배치해야함
    - { role: role-zsh, tags: 'zsh' }

