- import_role:
    name: ansible-role-zsh
  become: true
  vars:
    zsh_autosuggestions_bind_key: "^ "
    zsh_antigen_theme: robbyrussell
    zsh_antigen_bundles_extras:
    - vi-mode
    zsh_antigen_bundles:
    - docker-compose
    - { name: command-not-found, when: "{{ ansible_os_family != 'Darwin' }}" } # too slow on OSX
    - { name: brew, command: brew }
    - { name: docker, command: docker }
    - { name: docker-compose, command: docker-compose }
    - git-extras
    - gnu-utils
    - { name: pip, command: pip }
    - python
    - { name: tmux, command: tmux }
    - { name: go, command: go }
    - { name: rake, command: rake }
    - { name: symfony2, command: symfony }
    - { name: systemd, command: systemctl }
    - { name: vagrant, command: vagrant }
    - { name: viasite/server-scripts, command: dbdump }
    - { name: viasite-ansible/zsh-ansible-server, command: ansible-deploy }
    - zsh_reload

    # on zsh 4.3.10 autosuggestions breaks multiline commands with \
    - { name: zsh-users/zsh-autosuggestions, when: "{{ zsh_version | default(false) | version_compare('5.0', '>=') }}" }
    - popstas/zsh-command-time
    - { name: unixorn/autoupdate-antigen.zshplugin, when: "{{ zsh_update_interval > 0 }}" }
    - urbainvaes/fzf-marks # replaces jump plugin, mark, jump and Ctrl+G
    - "{{ fzf_widgets }}"
    # must be last, don't work on zsh < 4.3.17
    #- { name: zsh-users/zsh-syntax-highlighting, when: "{{ zsh_version | default(false) | version_compare('4.3.17', '>=') }}" }
    - { name: zdharma/fast-syntax-highlighting, when: "{{ zsh_version | default(false) | version_compare('4.3.17', '>=') }}" }

- name: touch .zshrc.local
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.local"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined

- name: ready copying .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local.before_ansible_manage_line"
    mode: 0644
  register: zshrc_local_copy_result

- name: copy .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local"
    mode: 0644
  when: zshrc_local_copy_result.changed

- name: "Clone fzf"
  git:
    repo: "https://github.com/junegunn/fzf.git"
    update: false
    dest: "~{{ ansible_user_id }}/.fzf"
  register: fzf_install_result

- name: "Install fzf"
  command: "~{{ ansible_user_id }}/.fzf/install --key-bindings --completion --no-update-rc"
  when: fzf_install_result.changed
