
- name: touch .zshrc.local
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.local"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined

- name: ready copying .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local.before_ansible_manage_line"
    mode: 0644
  register: zshrc_local_copy_result

- name: copy .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local"
    mode: 0644
  when: zshrc_local_copy_result.changed

- name: "Clone fzf"
  git:
    repo: "https://github.com/junegunn/fzf.git"
    update: false
    dest: "~{{ ansible_user_id }}/.fzf"
  register: fzf_install_result

- name: "Install fzf"
  become: true
  command: "~{{ ansible_user_id }}/.fzf/install --key-bindings --completion --no-update-rc"
  when: fzf_install_result.changed

- name: ensure tmuxinator packages is at the latest version
  gem:
    name: tmuxinator
    state: latest

- name: copy proxyrc file
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc"
    mode: 0644
    content: "{{ zsh_proxyrc }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: copy proxyrc-unset file
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc-unset"
    mode: 0644
    content: "{{ zsh_proxyrc_unset }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: delete proxyrc file
  file:
    path: "~{{ ansible_user_id }}/proxyrc"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- name: delete proxyrc-unset file
  file:
    path: "~{{ ansible_user_id }}/proxyrc-unset"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- name: install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present
  when: ansible_os_family == "RedHat"
- name: install ca package on debian systems
  apt:
    name: ca-certificates
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true
- name: enable dynamic ca configuration on rhel6
  shell: /bin/update-ca-trust enable
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: copy certificate authority to trusted ca path of the os
  copy:
    content: "{{ EXTRA_VAR_CA_CERT }}"
    dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/company.crt'
    owner: root
    group: root
    mode: 0644
  become: true
  when: EXTRA_VAR_PROXY_SERVER_URL is defined
  notify:
    - update trusted ca debian
    - update trusted ca redhat

- name: delete certificate
  file:
    path: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/company.crt'
    state: absent
  become: true
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined
  notify:
    - update trusted ca debian
    - update trusted ca redhat

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다
- blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR NVM'
    path: ~/.zshrc.local
    content: |-
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

- name: copy vagrant public key
  when: ansible_env.USER == "vagrant"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    line: "{{lookup('file', 'vagrant-key.pub') }}"
    create: true

