
- name: touch .zshrc.local
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.local"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined

- name: ready copying .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local.before_ansible_manage_line"
    mode: 0644
  register: zshrc_local_copy_result

- name: copy .zshrc.local
  copy:
    src: .zshrc.local
    dest: "~{{ ansible_user_id }}/.zshrc.local"
    mode: 0644
  when: zshrc_local_copy_result.changed

- name: "Clone fzf"
  git:
    repo: "https://github.com/junegunn/fzf.git"
    update: false
    dest: "~{{ ansible_user_id }}/.fzf"
  register: fzf_install_result

- name: "Install fzf"
  become: true
  command: "~{{ ansible_user_id }}/.fzf/install --key-bindings --completion --no-update-rc"
  when: fzf_install_result.changed
