
- name: create ~/.zshrc.template
  copy:
    src: .zshrc.template
    dest: "~{{ ansible_user_id }}/.zshrc.template"
    mode: 0644
  register: zshrc_template

- name: create ~/.zshrc.local if .zshrc.template changed
  copy:
    src: .zshrc.template
    dest: "~{{ ansible_user_id }}/.zshrc.local"
    mode: 0644
    remote_src: yes
  register: zshrc_local

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다.
- name: insert ls aliases for MacOS
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR LS_ALIASES'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    content: |-
      alias ls='/usr/local/bin/gls --color=auto'
      alias l='/usr/local/bin/gls -CF --color=auto'
      alias ll='/usr/local/bin/gls -alF --color=auto'
  when: ansible_os_family == 'Darwin' and zshrc_local.changed

- name: insert ls aliases for Ubuntu
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR LS_ALIASES'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    content: |-
      alias ls='/bin/ls --color=auto'
      alias l='/bin/ls -CF --color=auto'
      alias ll='/bin/ls -alF --color=auto'
  when: ansible_os_family == 'Debian' and zshrc_local.changed

- name: insert ls aliases for Ubuntu
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR CUSTOM_PROMPT'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    content: |-
      # On Chrome secure shell, if special character exists, bad cursor position problem occurs.
      PROMPT="%(?:%{$fg_bold[green]%}>:%{$fg_bold[red]%}>)"
      PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

      ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
      ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
      ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}x"
      ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
  when: EXTRA_VAR_NO_SPECIAL_CHAR_IN_PROMPT and zshrc_local.changed

- name: "nvm install"
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version | default('master') }}"
    dest: "{{ ansible_env.HOME }}/.nvm"
    depth: "1"
  with_items:
    - repo: https://github.com/nvm-sh/nvm.git

- name: "Clone LS_COLORS"
  git:
    repo: "https://github.com/trapd00r/LS_COLORS"
    update: false
    dest: "~{{ ansible_user_id }}/.dircolors"

