
- name: "copy {{ zsh_config }} to ~/.zshrc.viasite-angible.zsh.tmp"
  copy:
    src: "{{ zsh_config }}"
    dest: "~{{ zsh_user }}/.zshrc.viasite-angible.zsh.tmp"
    mode: '0644'
  changed_when: false

- name: copy ~/.zshrc.viasite-angible.zsh.tmp to ~/.zshrc.viasite-angible.zsh
  copy:
    src: "~{{ zsh_user }}/.zshrc.viasite-angible.zsh.tmp"
    dest: "~{{ zsh_user }}/.zshrc.viasite-angible.zsh"
    mode: '0644'
  register: zshrc_viasite_angible_zsh

- name: touch .zshrc
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff is defined and (touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined)

- name: create ~/.zshrc.user
  copy:
    src: .zshrc.user
    dest: "~{{ ansible_user_id }}/.zshrc.user"
    mode: 0644
  register: zshrc_user_file

- name: copy ~/.zshrc.user into ~/.zshrc
  copy:
    src: "~{{ ansible_user_id }}/.zshrc.user"
    dest: "~{{ ansible_user_id }}/.zshrc"
    mode: '0644'
    backup: yes
  when: zshrc_user_file.changed or zshrc_viasite_angible_zsh.changed
  register: zshrc

- name: insert viasite-angible.zsh into ~/.zshrc
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR viasite-ansible.zsh'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    block: "{{ lookup('file', '~/.zshrc.viasite-angible.zsh') }}"
  when: zshrc_user_file.changed or zshrc_viasite_angible_zsh.changed

- name: "nvm install"
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version | default('master') }}"
    dest: "{{ ansible_env.HOME }}/.nvm"
    depth: "1"
  with_items:
    - repo: https://github.com/nvm-sh/nvm.git

- name: "Clone LS_COLORS"
  git:
    repo: "https://github.com/trapd00r/LS_COLORS"
    update: false
    dest: "~{{ ansible_user_id }}/.dircolors"

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다
- name: insert ls aliases for MacOS
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR LS_ALIASES'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    content: |-
      alias ls='/usr/local/bin/gls --color=auto'
      alias l='/usr/local/bin/gls -CF --color=auto'
      alias ll='/usr/local/bin/gls -alF --color=auto'
  when: ansible_os_family == 'Darwin' and (zshrc_user_file.changed or zshrc_viasite_angible_zsh.changed)

- name: insert ls aliases for Ubuntu
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR LS_ALIASES'
    path: "~{{ ansible_user_id }}/.zshrc"
    mode: 0644
    content: |-
      alias ls='/bin/ls --color=auto'
      alias l='/bin/ls -CF --color=auto'
      alias ll='/bin/ls -alF --color=auto'
  when: ansible_os_family == 'Debian' and (zshrc_user_file.changed or zshrc_viasite_angible_zsh.changed)
