
- name: log
  debug:
    msg: task-git.yml

- name: touch .gitconfig
  file:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined

- name: copying .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig.before_insert_by_ansible
    mode: 0644
  register: gitconfig_copy_result

- name: copy .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    mode: '0644'
    backup: yes
  when: gitconfig_copy_result.changed

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다
- name: set hide-dirty in ~/.gitconfig
  blockinfile:
    marker: "  # {mark} ANSIBLE MANAGED BLOCK FOR GIT_HIDE_DIRTY"
    path: ~/.gitconfig
    content: "  hide-dirty = {{ '1' if ansible_env.USER == 'vagrant' else '0' }}"

- name: "Install git-p4-support-hangul"
  git:
    repo: https://gitlab.com/b6pzeusbc54tvhw5jgpyw8pwz2x6gs/git-p4-support-hangul.git
    dest: "{{ ansible_env.HOME }}/.git-p4-support-hangul"
    update: false
    depth: 1

- name: copy git-p4.py into /usr/local/bin/
  copy:
    src: "{{ ansible_env.HOME }}/.git-p4-support-hangul/git-p4.py"
    dest: /usr/local/bin/
    mode: preserve
    remote_src: true

# - debug:
#     var: git_p4_bin_src

- name: copy p4 into /usr/local/bin/
  copy:
    src: "{{ git_p4_bin_src }}"
    dest: /usr/local/bin/p4
    mode: preserve
    remote_src: true
