
- name: apt proxy configure
  become: true
  copy:
    content: "{{ apt_company_proxy }}"
    dest: /etc/apt/apt.conf.d/200company-proxy.conf
  when: ansible_os_family == "Debian"

- name: copy company.crt file into home directory
  copy:
    content: "{{ EXTRA_VAR_CA_CERT }}"
    dest: "~{{ ansible_user_id }}/company.crt"
  when: EXTRA_VAR_CA_CERT is defined

- name: delete company.crt file
  file:
    path: "~{{ ansible_user_id }}/company.crt"
    state: absent
  when: EXTRA_VAR_CA_CERT is not defined

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다
- blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PROXY"
    path: ~/.npmrc
    content: "{{ node_npmrc_proxy }}"

- name: copy proxyrc file
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc"
    mode: 0644
    content: "{{ zsh_proxyrc }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: copy proxyrc-unset file
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc-unset"
    mode: 0644
    content: "{{ zsh_proxyrc_unset }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: delete proxyrc file
  file:
    path: "~{{ ansible_user_id }}/proxyrc"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- name: delete proxyrc-unset file
  file:
    path: "~{{ ansible_user_id }}/proxyrc-unset"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- name: copy certificate authority to trusted ca path of the os
  copy:
    content: "{{ EXTRA_VAR_CA_CERT }}"
    dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/company.crt'
    owner: root
    group: root
    mode: 0644
  become: true
  when: EXTRA_VAR_PROXY_SERVER_URL is defined
  notify:
    - update trusted ca debian
    - update trusted ca redhat

- name: delete certificate
  file:
    path: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/company.crt'
    state: absent
  become: true
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined
  notify:
    - update trusted ca debian
    - update trusted ca redhat

- blockinfile:
    marker: "  # {mark} ANSIBLE MANAGED BLOCK FOR GIT_PROXY"
    path: "~{{ ansible_user_id }}/.gitconfig"
    content: "{{ git_proxy }}"
