- import_role:
    name: Stouts.python
  become: true
  vars:
    python_ppa: ppa:deadsnakes/ppa
    python_versions: ["3.6"]

- import_role:
    name: geerlingguy.pip
  become: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: awscli
        state: latest
