- name: create ~/.hammerspoon directory
  file:
    path: ~/.hammerspoon
    state: directory
    mode: 0755

  # VIM Editor, VS Code, Idea에서 VIM 사용 시
  # insert mode에서 한글 입력 후 command mode로 나왔을 때 자동 영문 전환을 위한
  # [Hammerspoon][https://www.hammerspoon.org/] lua 스크립트.
- name: copying hammerspoon init.lua
  copy:
    backup: yes
    src: hammerspoon-init.lua
    dest: ~/.hammerspoon/init.lua
    mode: 0644

- name: create ~/.config/karabiner directory
  file:
    path: ~/.config/karabiner
    state: directory
    mode: 0755

- name: copying karabiner.json
  copy:
    backup: yes
    src: karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644

- homebrew_tap:
    name: aws/tap

- name: (without sudo password) brew install vim
  community.general.homebrew:
    name:
      - vim
    state: present

- name: (without sudo password) brew install ripgrep the_silver_searcher
  community.general.homebrew:
    name:
      - ripgrep
      - the_silver_searcher
    state: present

- name: (without sudo password) brew install jq direnv fasd
  community.general.homebrew:
    name:
      - jq
      - direnv
      - fasd
    state: present

- name: (without sudo password) brew install thefuck tree coreutils curl fzf
  community.general.homebrew:
    name:
      - thefuck
      - tree
      - coreutils
      - curl
      - fzf
    state: present

- name: (without sudo password) brew install awscli aws-sam-cli
  community.general.homebrew:
    name:
      - awscli
      - aws-sam-cli
    state: present

- name: (without sudo password) brew install --cask iterm2
  community.general.homebrew_cask:
    name:
      - iterm2
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask slack notion zoom
  community.general.homebrew_cask:
    name:
      - slack
      - notion
      - zoom
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask bettertouchtool
  community.general.homebrew_cask:
    name:
      - bettertouchtool
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask obs
  community.general.homebrew_cask:
    name:
      - obs
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask docker
  community.general.homebrew_cask:
    name:
      - docker
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask alfred hammerspoon
  community.general.homebrew_cask:
    name:
      - alfred
      - hammerspoon
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask google-chrome firefox
  community.general.homebrew_cask:
    name:
      - google-chrome
      - firefox
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask visual-studio-code intellij-idea-ce
  community.general.homebrew_cask:
    name:
      - visual-studio-code
      - intellij-idea-ce
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask synergy
  community.general.homebrew_cask:
    name:
      - synergy
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask send-anywhere
  community.general.homebrew_cask:
    name:
      - send-anywhere
    greedy: yes
    state: present

- name: (without sudo password) brew install --cask keyboard-maestro
  community.general.homebrew_cask:
    name:
      - keyboard-maestro
    greedy: yes
    state: present

- name: (with sudo password) brew install --cask karabiner-elements gureumkim
  community.general.homebrew_cask:
    name:
      - karabiner-elements
      - gureumkim
    greedy: yes
    state: present
    sudo_password: "{{ ansible_become_pass }}"
