- name: Install a brew packages for Darwin
  homebrew:
    name:
      - ripgrep
      - jq
      - direnv
      - thefuck
      - yarn
      - the_silver_searcher
      - fzf
      - git
      - fasd
      - tree
      - zsh
      - wget
      - coreutils
    state: latest
    update_homebrew: yes

- name: Install a brew cask app
  homebrew_cask:
    name:
      - firefox
      - google-chrome
      - slack
      - visual-studio-code
      - skitch
      - webtorrent
      - keyboard-maestro
      - karabiner-elements
      - alfred
      - send-anywhere
      - notion
      - obs
    state: present
    update_homebrew: yes

