- name: Install a brew packages for Darwin
  homebrew:
    name:
      - ripgrep
      - jq
      - direnv
      - thefuck
      - yarn
      - the_silver_searcher
      - fzf
      - git
      - fasd
      - tree
      - zsh
      - wget
      - coreutils
      - curl
    state: latest
    update_homebrew: yes

- name: copying hammerspoon init.lua
  copy:
    src: init.lua
    dest: ~/.hammerspoon/init.lua
    mode: 0644

- name: copying karabiner.json
  copy:
    src: karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644

- name: Install a brew cask app - 1
  homebrew_cask:
    name:
      #- lastpass  # app store version 이 좋다
      - google-chrome
      - visual-studio-code
      - skitch
      - keyboard-maestro
    state: present
    update_homebrew: yes
    sudo_password: "{{ ansible_ssh_pass }}"

- name: Install a brew cask app - 2
  homebrew_cask:
    name:
      - karabiner-elements
      - send-anywhere
      - iterm2
      - firefox
    state: present
    update_homebrew: no
    sudo_password: "{{ ansible_ssh_pass }}"


- name: Install a brew cask app - 3
  homebrew_cask:
    name:
      - slack
      - webtorrent
      - notion
      - obs
    state: present
    update_homebrew: no
    sudo_password: "{{ ansible_ssh_pass }}"

- name: Install a brew cask app - 4
  homebrew_cask:
    name:
      - docker
      - alfred
      - hammerspoon
      - bettertouchtool
    state: present
    update_homebrew: no
    sudo_password: "{{ ansible_ssh_pass }}"

