- name: create ~/.hammerspoon directory
  file:
    path: ~/.hammerspoon
    state: directory
    mode: 0755

  # VIM Editor, VS Code, Idea에서 VIM 사용 시
  # insert mode에서 한글 입력 후 command mode로 나왔을 때 자동 영문 전환을 위한
  # [Hammerspoon][https://www.hammerspoon.org/] lua 스크립트.
- name: copying hammerspoon init.lua
  copy:
    backup: yes
    src: hammerspoon-init.lua
    dest: ~/.hammerspoon/init.lua
    mode: 0644

- name: create ~/.config/karabiner directory
  file:
    path: ~/.config/karabiner
    state: directory
    mode: 0755

- name: copying karabiner.json
  copy:
    backup: yes
    src: karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644

- homebrew_tap:
    name: aws/tap

- name: Install brew apps Using without sudo password
  community.general.homebrew:
    name:
      - vim
      - ripgrep
      - jq
      - direnv
      - thefuck
      - the_silver_searcher
      - fasd
      - tree
      - coreutils
      - curl
      - fzf
      - awscli
      - aws-sam-cli
    state: present

- name: Install brew cask apps Using without sudo password
  community.general.homebrew_cask:
    name:
      - iterm2
      - slack
      - bettertouchtool
      - notion
      - obs
      - docker
      - alfred
      - hammerspoon
      - firefox
      - intellij-idea-ce
      - google-chrome
      - synergy
      - visual-studio-code
      - intellij-idea-ce
      - send-anywhere
      # 다운을 못받는 네트워크 환경이 있다.
      # 필요하면 주석치고 넘어 간 후 network 변경해서 주석풀고 처리
      - keyboard-maestro
    greedy: yes
    state: present

- name: Install apps Using sudo password for installing cask
  community.general.homebrew_cask:
    name:
      - karabiner-elements
      - gureumkim
    greedy: yes
    state: present
    sudo_password: "{{ ansible_become_pass }}"
