
- name: ensure ppa:aacebedo/fasd is present
  become: true
  apt_repository:
    repo: ppa:aacebedo/fasd
    state: present
    update_cache: false

- name: Configure the Yarn APT key
  become: true
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  become: true
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
    update_cache: false

- name: ensure apt packages is at the latest version
  become: true
  when: ansible_os_family == "Debian"
  apt:
    install_recommends: false
    update_cache: true
    state: latest
    name:
      - direnv
      - jq
      - curl
      - python-pkg-resources
      - gcc
      - thefuck
      - silversearcher-ag
      - xclip
      - yarn
      - git
      - git-extras
      - fasd
      - tree

- name: Check if ripgrep is installed
  shell: "command -v rg || which rg"
  register: ripgrep_is_installed
  changed_when: false
  failed_when: false

- name: Install a ripgrep for Debian
  become: true
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.9.0/ripgrep_0.9.0_amd64.deb
  when: ripgrep_is_installed.rc != 0 and ansible_os_family == "Debian"

- name: Install a brew packages for Darwin
  when: ansible_os_family == "Darwin"
  homebrew:
    name:
      - ripgrep
      - jq
      - direnv
      - thefuck
      - yarn
      - the_silver_searcher
      - fzf
      - git
      - git-extras
      - fasd
      - tree
    state: latest
    update_homebrew: no

