- name: ensure ppa:aacebedo/fasd is present
  become: true
  apt_repository:
    repo: ppa:aacebedo/fasd
    state: present
    update_cache: false
  when: ansible_os_family == "Debian"

- name: ensure apt packages is at the latest version
  become: true
  when: ansible_os_family == "Debian"
  apt:
    install_recommends: false
    update_cache: true
    state: latest
    name:
      - vim
      - direnv
      - jq
      - curl
      - python-pkg-resources
      - gcc
      - thefuck
      - silversearcher-ag
      - xclip
      - git
      - git-extras
      - fasd
      - tree
      - ripgrep

# - name: Check if ripgrep is installed
#   shell: "command -v rg || which rg"
#   register: ripgrep_is_installed
#   changed_when: false
#   failed_when: false

# - name: Install a ripgrep for Debian
#   become: true
#   apt:
#     deb: https://github.com/BurntSushi/ripgrep/releases/download/0.9.0/ripgrep_0.9.0_amd64.deb
#   when: ripgrep_is_installed.rc != 0 and ansible_os_family == "Debian"
